apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-hostpid
  name: busybox-hostpid
spec:
  hostPID: true
  containers:
  - image: busybox
    name: busybox
  restartPolicy: Never
status: {}
