apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-hostipc
  name: busybox-hostipc
spec:
  hostIPC: true
  containers:
  - image: busybox
    name: busybox
  restartPolicy: Never
status: {}
