apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8sadmission
  name: k8sadmission
  namespace: k8sadmission
spec:
  progressDeadlineSeconds: 600
  replicas: 1 # Can be HA
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8sadmission
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8sadmission
    spec:
      automountServiceAccountToken: false
      containers:
      - image: "docker.io/library/k8sadmission:latest"
        imagePullPolicy: IfNotPresent
        name: k8sadmission
        # command: # Adding example for overrides
        # - "/k8sadmission"
        # args:
        # - "--logger-max-backups=1" # Example of reducing number of files stored
        resources:
          requests:
            cpu:  "2m"
            memory: "10Mi"
          # limits:
          #   cpu: "1"
          #   memory: "32Mi"
        ports:
        - containerPort: 8443
          protocol: TCP
          name: https
        - containerPort: 55555
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: certs
          mountPath: "/etc/tls"
          readOnly: true
        - name: config
          mountPath: /etc/falco/falco.yaml
          subPath: falco.yaml
        - name: rules
          mountPath: /etc/falco/k8s_admission_rules.yaml
          subPath: k8s_admission_rules.yaml.yaml
        - name: tmp
          mountPath: "/tmp"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: 
            - ALL 
      securityContext:
        runAsUser: 255999 # Already true in the container, but does no harm to be explicit
        runAsGroup: 255999
        fsGroup: 255999
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          secretName: k8sadmission
      - name: rules
        configMap:
          name: falcorules
      - name: config
        configMap:
          name: falcoyaml
      - name: tmp
        emptyDir:
          sizeLimit: 2Gi # Based on default of 3 files at 500Mi
